// <auto-generated />
using Board_Game_Software.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Board_Game_Software.Migrations
{
    [DbContext(typeof(BoardGameDbContext))]
    [Migration("20260702224500_AddClubScopedReferenceData")]
    partial class AddClubScopedReferenceData
    {
    }
}
